// Automatically generated by astro-icon
// 5b1ccc0ce5ac84a11fd5982dfb24b3f9ef8fe4596e7a53f821e229d2ef6adf36

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "angle-left"
		| "angle-right"
		| "github"
		| "mastodon"
		| "rocket";
}